FROM golang:1.20.2 AS builder
WORKDIR /go/src/kyanite
COPY . .
RUN go install -v github.com/swaggo/swag/cmd/swag@latest && \
    go mod download && \
    go mod verify && \
    make && \
    chmod +x /go/src/kyanite/kyanite

FROM scratch
COPY --from=builder /go/src/kyanite/kyanite /
ENTRYPOINT ["/kyanite"]