FROM golang:1.19.5 AS builder
WORKDIR /go/src/kyanite
COPY . .
RUN export GOPROXY=https://goproxy.io,direct && \
    go install -v github.com/swaggo/swag/cmd/swag@latest && \
    go mod download && \
    go mod verify && \
    make && \
    chmod +x /go/src/kyanite/kyanite

# Kyanite image from google distroless base image
# only one static app bin file
# suit for production running
FROM gcr.io/distroless/static-debian11
COPY --from=builder /go/src/kyanite/kyanite /
ENTRYPOINT ["/kyanite"]