FROM golang:1.19.5 AS builder
WORKDIR /go/src/kyanite
COPY . .
RUN go install -v github.com/swaggo/swag/cmd/swag@latest && \
    go mod download && \
    go mod verify && \
    make && \
    chmod +x /go/src/kyanite/kyanite

# Kyanite image from debian 11 base image
# build whit a lot of ops tools
# suit for learn/ops use
FROM debian:11

RUN apt update && \
    apt-get install -y --no-install-recommends apt-file curl tcpdump bind9-dnsutils telnet file net-tools iproute2 inetutils-ping  && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*
COPY --from=builder /go/src/kyanite/kyanite /
ENTRYPOINT ["/kyanite"]